services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    build:
      context: requirements/mariadb
      dockerfile: dockerfile
    env_file:
      - .env
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception-network

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:

volumes: 
  mariadb-data:
  wordpress-data:

networks:
  inception-network:
    name: inception-network
    driver: bridge